### ISSUE TITLE
您好，想请教下您 dpc ip核的一些问题

### ISSUE THREAD

**Issue by Rui-R** [bxinquan/zynqmp_cam_isp_demo#1]
作者您好，感谢您的工作。我目前想尝试使用dpc(defect pixel correct) ip核处理单通道图像视频流，原代码应该是处理4通道bayer图像的，请问应该如何修改以处理单通道图像呢，希望得到您的解答，谢谢。

**Comment by bxinquan** [comment]
代码中有注释哇
/*
 * bayer 5x5邻域内同意颜色通道相对于中心像素都有8个临近像素。矫正按以下步骤操作：
 * 计算中心像素与周围八个像素值的差；
 * 判断八个差值是否都为正值或者都为负值；
 * 如果有的为正有的为负，那么就为正常值，否则进行下一步；
 * 设置一个阈值，如果八个差值的绝对值都查过阈值，那么就判断为坏点；
 * 判断为坏点后就用八个临近的像素值的中位值来替换当前的像素值；
*/

**Comment by Rui-R** [comment]
好的哥，能加个联系方式咱详细聊下吗，有些问题想请教您。
